credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$Rw6ak/2KlXjQ1E18n0NyoeheTWKINkzksTCWCMvtL2JPObunRFLEK # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$8snZOfokc/08GfaXqnAGpe3c5Uqe002kt7UzgrDIqZZqgw7sjOa.S # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com