investor_data_variations = [
    {
        'investment_company': 'Alpha Investments LLC',
        'investor_type': ['VC Fund', 'Corporate Venture'],
        'investor_description': 'Investing in early-stage fintech and healthtech startups.',
        'investor_expertise': ['Finance', 'Strategy'],
        'preferred_attributes': ['Great Team', 'Recurring Revenue', 'Positive Unit Economics'],
        'preferred_business_priority': ['Customer Acquisition', 'Product Development'],
        'preferred_founder_gender': ['Female', 'Male'],
        'preferred_investment_round': ['Seed', 'Series A'],
        'preferred_industry': ['Fintech', 'Healthtech'],
        'preferred_country': ['USA', 'UK'],
        'min_investment': 50000.0,
        'max_investment': 300000.0,
        'past_investments': 1500000.0,
        'successful_exits': 8,
        'preferred_startup_age_min': 2,
        'preferred_startup_age_max': 5,
        'preferred_business_model': ['Subscription', 'SaaS'],
        'preferred_business_stage': ['MVP', 'Scaling'],
        'preferred_engagement_length': ['Medium-term (1-3 years)'],
        'preferred_engagement_model': ['Advisory', 'Strategic Partnership'],
        'preferred_team_size_min': 5,
        'preferred_team_size_max': 20,
    },
    {
        'investment_company': 'Beta Capital Group',
        'investor_type': ['Angel Investor', 'Family Office'],
        'investor_description': 'Supporting innovative startups in the green technology sector.',
        'investor_expertise': ['GreenTech/Environment', 'Legal'],
        'preferred_attributes': ['Patented Technology', 'Scalable Model'],
        'preferred_business_priority': ['Technology Enhancement', 'Geographic Expansion'],
        'preferred_founder_gender': ['Female'],
        'preferred_investment_round': ['Preseed', 'Seed'],
        'preferred_industry': ['GreenTech/Environment'],
        'preferred_country': ['USA'],
        'min_investment': 10000.0,
        'max_investment': 50000.0,
        'past_investments': 800000.0,
        'successful_exits': 4,
        'preferred_startup_age_min': 1,
        'preferred_startup_age_max': 3,
        'preferred_business_model': ['B2B', 'Subscription'],
        'preferred_business_stage': ['Idea', 'Prototype'],
        'preferred_engagement_length': ['Short-term (Less than 1 year)'],
        'preferred_engagement_model': ['Hands-on'],
        'preferred_team_size_min': 2,
        'preferred_team_size_max': 10,
    },
    {
        'investment_company': 'Gamma Venture Partners',
        'investor_type': ['VC Fund', 'Syndicate'],
        'investor_description': 'Investing in high-growth potential tech startups.',
        'investor_expertise': ['Tech', 'Marketing'],
        'preferred_attributes': ['Recurring Revenue', 'Scalable Model', 'Large Market Size'],
        'preferred_business_priority': ['Product Development', 'Technology Enhancement'],
        'preferred_founder_gender': ['Male'],
        'preferred_investment_round': ['Series A', 'Series B'],
        'preferred_industry': ['AI & ML', 'E-commerce'],
        'preferred_country': ['USA', 'UK'],
        'min_investment': 100000.0,
        'max_investment': 500000.0,
        'past_investments': 2000000.0,
        'successful_exits': 5,
        'preferred_startup_age_min': 3,
        'preferred_startup_age_max': 7,
        'preferred_business_model': ['B2B', 'SaaS'],
        'preferred_business_stage': ['MVP', 'Scaling'],
        'preferred_engagement_length': ['Medium-term (1-3 years)'],
        'preferred_engagement_model': ['Advisory', 'Mentorship'],
        'preferred_team_size_min': 10,
        'preferred_team_size_max': 30,
    },
    {
        'investment_company': 'Delta Funding Corp.',
        'investor_type': ['Corporate Venture', 'Crowdfunding'],
        'investor_description': 'Supporting startups with innovative business models.',
        'investor_expertise': ['Finance', 'Strategy', 'Sales'],
        'preferred_attributes': ['Initial Customers', 'Recurring Revenue'],
        'preferred_business_priority': ['Customer Acquisition', 'Marketing Spend'],
        'preferred_founder_gender': ['Female', 'Male'],
        'preferred_investment_round': ['Seed', 'Series A'],
        'preferred_industry': ['Fintech', 'Healthtech'],
        'preferred_country': ['UK', 'South Africa'],
        'min_investment': 30000.0,
        'max_investment': 200000.0,
        'past_investments': 1000000.0,
        'successful_exits': 7,
        'preferred_startup_age_min': 2,
        'preferred_startup_age_max': 5,
        'preferred_business_model': ['Marketplace', 'Subscription'],
        'preferred_business_stage': ['Prototype', 'MVP'],
        'preferred_engagement_length': ['Short-term (Less than 1 year)'],
        'preferred_engagement_model': ['Hands-on'],
        'preferred_team_size_min': 5,
        'preferred_team_size_max': 15,
    },
        # ... (continuing from the previous entries)
    {
        'investment_company': 'InnoInvest Group',
        'investor_type': ['Family Office', 'Crowdfunding'],
        'investor_description': 'Focused on early-stage tech startups.',
        'investor_expertise': ['Tech', 'Strategy'],
        'preferred_attributes': ['Great Team', 'Recurring Revenue'],
        'preferred_business_priority': ['Prototype Development', 'Marketing Spend'],
        'preferred_founder_gender': ['Male'],
        'preferred_investment_round': ['Preseed', 'Seed'],
        'preferred_industry': ['Insuretech', 'E-commerce'],
        'preferred_country': ['USA', 'Canada'],
        'min_investment': 50000.0,
        'max_investment': 250000.0,
        'past_investments': 1500000.0,
        'successful_exits': 3,
        'preferred_startup_age_min': 1,
        'preferred_startup_age_max': 3,
        'preferred_business_model': ['B2B', 'Marketplace'],
        'preferred_business_stage': ['Idea', 'Prototype'],
        'preferred_engagement_length': ['Short-term (Less than 1 year)'],
        'preferred_engagement_model': ['Mentorship'],
        'preferred_team_size_min': 2,
        'preferred_team_size_max': 10,
    },
    {
        'investment_company': 'Prosperity Ventures',
        'investor_type': ['Angel Investor', 'VC Fund'],
        'investor_description': 'Investing in disruptive technologies.',
        'investor_expertise': ['Tech', 'Legal'],
        'preferred_attributes': ['Patented Technology', 'Scalable Model'],
        'preferred_business_priority': ['Technology Enhancement', 'Hiring Talent'],
        'preferred_founder_gender': ['Female'],
        'preferred_investment_round': ['Seed', 'Series A'],
        'preferred_industry': ['AI & ML', 'Biotech'],
        'preferred_country': ['USA', 'UK'],
        'min_investment': 100000.0,
        'max_investment': 500000.0,
        'past_investments': 2500000.0,
        'successful_exits': 6,
        'preferred_startup_age_min': 2,
        'preferred_startup_age_max': 6,
        'preferred_business_model': ['SaaS', 'Subscription'],
        'preferred_business_stage': ['MVP', 'Product-Market Fit'],
        'preferred_engagement_length': ['Medium-term (1-3 years)'],
        'preferred_engagement_model': ['Advisory'],
        'preferred_team_size_min': 5,
        'preferred_team_size_max': 20,
    },
    {
        'investment_company': 'TechFront Ventures',
        'investor_type': ['VC Fund', 'Corporate Venture'],
        'investor_description': 'Investing in the future of technology.',
        'investor_expertise': ['Tech', 'Strategy', 'Operations'],
        'preferred_attributes': ['Patented Technology', 'Scalable Model'],
        'preferred_business_priority': ['Technology Enhancement', 'Hiring Talent'],
        'preferred_founder_gender': ['Female', 'Male'],
        'preferred_investment_round': ['Seed', 'Series A'],
        'preferred_industry': ['AI & ML', 'Biotech'],
        'preferred_country': ['USA', 'UK'],
        'min_investment': 50000.0,
        'max_investment': 300000.0,
        'past_investments': 2000000.0,
        'successful_exits': 5,
        'preferred_startup_age_min': 1,
        'preferred_startup_age_max': 5,
        'preferred_business_model': ['SaaS', 'Subscription'],
        'preferred_business_stage': ['MVP', 'Scaling'],
        'preferred_engagement_length': ['Medium-term (1-3 years)'],
        'preferred_engagement_model': ['Strategic Partnership'],
        'preferred_team_size_min': 5,
        'preferred_team_size_max': 20,
    },
    {
        'investment_company': 'GreenShoots Capital',
        'investor_type': ['Angel Investor', 'Family Office'],
        'investor_description': 'Empowering sustainable and eco-friendly startups.',
        'investor_expertise': ['Finance', 'GreenTech/Environment'],
        'preferred_attributes': ['Large Market Size', 'Scalable Model'],
        'preferred_business_priority': ['Product Development', 'Geographic Expansion'],
        'preferred_founder_gender': ['Female'],
        'preferred_investment_round': ['Preseed', 'Seed'],
        'preferred_industry': ['GreenTech/Environment', 'Agritech'],
        'preferred_country': ['Kenya', 'South Africa'],
        'min_investment': 25000.0,
        'max_investment': 150000.0,
        'past_investments': 800000.0,
        'successful_exits': 2,
        'preferred_startup_age_min': 2,
        'preferred_startup_age_max': 6,
        'preferred_business_model': ['B2C', 'Marketplace'],
        'preferred_business_stage': ['Prototype', 'MVP'],
        'preferred_engagement_length': ['Long-term (More than 3 years)'],
        'preferred_engagement_model': ['Hands-on'],
        'preferred_team_size_min': 3,
        'preferred_team_size_max': 15,
    },
    {
        'investment_company': 'Skyline Investors',
        'investor_type': ['Corporate Venture', 'Syndicate'],
        'investor_description': 'Backing innovative urban development projects.',
        'investor_expertise': ['Real Estate', 'Finance'],
        'preferred_attributes': ['Large Market Size', 'Brand Recognition'],
        'preferred_business_priority': ['Geographic Expansion', 'Technology Enhancement'],
        'preferred_founder_gender': ['Male'],
        'preferred_investment_round': ['Series B', 'Series C'],
        'preferred_industry': ['Real Estate', 'Transportation'],
        'preferred_country': ['USA', 'UK'],
        'min_investment': 200000.0,
        'max_investment': 1000000.0,
        'past_investments': 5000000.0,
        'successful_exits': 8,
        'preferred_startup_age_min': 3,
        'preferred_startup_age_max': 8,
        'preferred_business_model': ['B2B', 'Direct to Consumer'],
        'preferred_business_stage': ['Growth', 'Scaling'],
        'preferred_engagement_length': ['Medium-term (1-3 years)'],
        'preferred_engagement_model': ['Advisory'],
        'preferred_team_size_min': 10,
        'preferred_team_size_max': 50,
    },
    {
        'investment_company': 'EdTech Innovators Fund',
        'investor_type': ['Government Fund', 'Crowdfunding'],
        'investor_description': 'Supporting education technology innovations.',
        'investor_expertise': ['Education', 'Tech'],
        'preferred_attributes': ['Great Team', 'Recurring Revenue'],
        'preferred_business_priority': ['Product Development', 'Customer Acquisition'],
        'preferred_founder_gender': ['Female', 'Male'],
        'preferred_investment_round': ['Seed', 'Series A'],
        'preferred_industry': ['Edutainment', 'Education'],
        'preferred_country': ['USA', 'Canada'],
        'min_investment': 10000.0,
        'max_investment': 100000.0,
        'past_investments': 300000.0,
        'successful_exits': 1,
        'preferred_startup_age_min': 0,
        'preferred_startup_age_max': 4,
        'preferred_business_model': ['Subscription', 'B2C'],
        'preferred_business_stage': ['Idea', 'Prototype'],
        'preferred_engagement_length': ['Medium-term (1-3 years)'],
        'preferred_engagement_model': ['Advisory'],
        'preferred_team_size_min': 10,
        'preferred_team_size_max': 50,
    }
]


startup_data_variations = [
    {
        'startup_company': 'TechFlow Inc.',
        'startup_website': 'https://techflow.com',
        'startup_stage': 'MVP',
        'startup_industries': ['Fintech', 'Edutainment'],
        'startup_countries': 'USA',
        'startup_age': 3,
        'mission': 'Empowering financial literacy through interactive educational platforms.',
        'long_term_goals': 'Become the leading provider of financial education in the US.',
        'current_capital': 15000.0,
        'current_investment': 20000.0,
        'investment_needed': 30000.0,
        'business_priorities': ['Customer Acquisition', 'Product Development'],
        'founder_name': 'Emily Smith',
        'founder_positions': ['CEO', 'CFO'],
        'founder_gender': 'Female',
        'team_size': 15,
        'key_team_expertise': ['Finance', 'Marketing', 'Strategy'],
        'product_description': 'An interactive platform for financial education.',
        'business_models': ['Subscription', 'B2C'],
        'product_stages': 'Prototype',
        'monthly_users': 5000,
        'investor_attributes': ['Revenue Growth', 'Great Team'],
        'investment_round': 'Seed',
        'investor_expertise': ['Finance', 'Marketing'],
        'engagement_lengths': ['Medium-term (1-3 years)'],
        'engagement_models': ['Mentorship'],
        'revenue_models': ['Subscription'],
        'revenue': 5000.0,
        'profit_margin': 0.2,
        'churn_rate': 5.0,
        'intellectual_properties': ['Trademarks'],
        'competitive_advantage': 'Unique interactive content.',
        'current_challenges': 'User acquisition and funding.'
    },
        {
        'startup_company': 'GreenInnovate Co.',
        'startup_website': 'https://greeninnovate.com',
        'startup_stage': 'Growth',
        'startup_industries': ['GreenTech/Environment', 'Agritech'],
        'startup_countries': 'UK',
        'startup_age': 5,
        'mission': 'Promoting sustainable agriculture through innovative technologies.',
        'long_term_goals': 'Expand sustainable practices across Europe and beyond.',
        'current_capital': 50000.0,
        'current_investment': 75000.0,
        'investment_needed': 100000.0,
        'business_priorities': ['Technology Enhancement', 'Geographic Expansion'],
        'founder_name': 'John Green',
        'founder_positions': ['CEO', 'CTO'],
        'founder_gender': 'Male',
        'team_size': 25,
        'key_team_expertise': ['Tech', 'Strategy', 'Operations'],
        'product_description': 'A suite of tools for sustainable farming.',
        'business_models': ['B2B', 'Subscription'],
        'product_stages': 'Scaling',
        'monthly_users': 15000,
        'investor_attributes': ['Scalable Model', 'Patented Technology'],
        'investment_round': 'Series A',
        'investor_expertise': ['Tech', 'Strategy'],
        'engagement_lengths': ['Long-term (More than 3 years)'],
        'engagement_models': ['Strategic Partnership'],
        'revenue_models': ['B2B', 'Subscription'],
        'revenue': 30000.0,
        'profit_margin': 0.25,
        'churn_rate': 3.0,
        'intellectual_properties': ['Patents', 'Trade Secrets'],
        'competitive_advantage': 'Patented technology and first-mover advantage.',
        'current_challenges': 'Competitor advancements and market saturation.'
    },
    {
        'startup_company': 'EdTechSphere LLC',
        'startup_website': 'https://edtechsphere.com',
        'startup_stage': 'Product-Market Fit',
        'startup_industries': ['Edutainment', 'E-commerce'],
        'startup_countries': 'USA',
        'startup_age': 2,
        'mission': 'Redefining learning through engaging and interactive platforms.',
        'long_term_goals': 'To be a global leader in educational technologies.',
        'current_capital': 30000.0,
        'current_investment': 40000.0,
        'investment_needed': 50000.0,
        'business_priorities': ['Customer Acquisition', 'Marketing Spend'],
        'founder_name': 'Sarah Johnson',
        'founder_positions': ['CEO', 'CMO'],
        'founder_gender': 'Female',
        'team_size': 20,
        'key_team_expertise': ['Marketing', 'Tech', 'Sales'],
        'product_description': 'An online marketplace for educational resources.',
        'business_models': ['Marketplace', 'E-commerce'],
        'product_stages': 'Profitable',
        'monthly_users': 25000,
        'investor_attributes': ['Revenue Growth', 'Large Market Size'],
        'investment_round': 'Seed',
        'investor_expertise': ['Marketing', 'Sales'],
        'engagement_lengths': ['Medium-term (1-3 years)'],
        'engagement_models': ['Advisory'],
        'revenue_models': ['Marketplace', 'E-commerce'],
        'revenue': 40000.0,
        'profit_margin': 0.15,
        'churn_rate': 4.0,
        'intellectual_properties': ['Trademarks'],
        'competitive_advantage': 'Exclusive partnerships with educational institutions.',
        'current_challenges': 'Increasing user base and brand recognition.'
    },
        {
        'startup_company': 'HealthGuard Solutions',
        'startup_website': 'https://healthguard.com',
        'startup_stage': 'Scaling',
        'startup_industries': ['Healthtech', 'AI & ML'],
        'startup_countries': 'USA',
        'startup_age': 3,
        'mission': 'Utilizing AI to improve healthcare accessibility.',
        'long_term_goals': 'Expand our AI healthcare solutions globally.',
        'current_capital': 70000.0,
        'current_investment': 100000.0,
        'investment_needed': 80000.0,
        'business_priorities': ['Technology Enhancement', 'Hiring Talent'],
        'founder_name': 'Dr. Emma Watson',
        'founder_positions': ['CEO', 'CIO'],
        'founder_gender': 'Female',
        'team_size': 15,
        'key_team_expertise': ['Tech', 'Healthcare'],
        'product_description': 'AI-powered diagnostic and patient management system.',
        'business_models': ['B2B', 'SaaS'],
        'product_stages': 'Profitable',
        'monthly_users': 10000,
        'investor_attributes': ['Scalable Model', 'Patented Technology'],
        'investment_round': 'Series B',
        'investor_expertise': ['Tech', 'Healthcare'],
        'engagement_lengths': ['Long-term (More than 3 years)'],
        'engagement_models': ['Strategic Partnership'],
        'revenue_models': ['SaaS'],
        'revenue': 20000.0,
        'profit_margin': 0.2,
        'churn_rate': 5.0,
        'intellectual_properties': ['Patents', 'Trademarks'],
        'competitive_advantage': 'Advanced AI algorithms and partnerships with hospitals.',
        'current_challenges': 'Navigating regulatory compliance and data privacy.'
    },
    {
        'startup_company': 'EcoHomes Inc.',
        'startup_website': 'https://ecohomes.com',
        'startup_stage': 'MVP',
        'startup_industries': ['Real Estate', 'GreenTech/Environment'],
        'startup_countries': 'UK',
        'startup_age': 2,
        'mission': 'Developing eco-friendly and affordable housing solutions.',
        'long_term_goals': 'Reduce the carbon footprint of residential buildings.',
        'current_capital': 40000.0,
        'current_investment': 50000.0,
        'investment_needed': 60000.0,
        'business_priorities': ['Product Development', 'Prototype Development'],
        'founder_name': 'Michael Turner',
        'founder_positions': ['CEO', 'CDO'],
        'founder_gender': 'Male',
        'team_size': 10,
        'key_team_expertise': ['Design', 'GreenTech/Environment'],
        'product_description': 'Eco-friendly modular homes.',
        'business_models': ['B2C', 'Direct to Consumer'],
        'product_stages': 'Prototype',
        'monthly_users': 300,
        'investor_attributes': ['Prototype', 'Great Team'],
        'investment_round': 'Preseed',
        'investor_expertise': ['Real Estate', 'GreenTech/Environment'],
        'engagement_lengths': ['Medium-term (1-3 years)'],
        'engagement_models': ['Hands-on'],
        'revenue_models': ['Direct to Consumer'],
        'revenue': 0,
        'profit_margin': 0,
        'churn_rate': 0,
        'intellectual_properties': ['Design Rights'],
        'competitive_advantage': 'Innovative design and eco-friendly materials.',
        'current_challenges': 'Raising funds for scaling production.'
    },
        {
        'startup_company': 'GameSphere Studios',
        'startup_website': 'https://gamesphere.com',
        'startup_stage': 'Growth',
        'startup_industries': ['Immersive Entertainment and Technology', 'E-sports'],
        'startup_countries': 'USA',
        'startup_age': 4,
        'mission': 'Creating immersive gaming experiences for a global audience.',
        'long_term_goals': 'Become a leading name in the global gaming industry.',
        'current_capital': 150000.0,
        'current_investment': 200000.0,
        'investment_needed': 100000.0,
        'business_priorities': ['Marketing Spend', 'Geographic Expansion'],
        'founder_name': 'Alex Johnson',
        'founder_positions': ['CEO', 'CDO'],
        'founder_gender': 'Male',
        'team_size': 25,
        'key_team_expertise': ['Tech', 'Marketing'],
        'product_description': 'A cross-platform multiplayer game with VR support.',
        'business_models': ['B2C', 'Subscription'],
        'product_stages': 'Profitable',
        'monthly_users': 500000,
        'investor_attributes': ['Recurring Revenue', 'Large Market Size'],
        'investment_round': 'Series A',
        'investor_expertise': ['Marketing', 'Strategy'],
        'engagement_lengths': ['Medium-term (1-3 years)'],
        'engagement_models': ['Strategic Partnership', 'Mentorship'],
        'revenue_models': ['Subscription'],
        'revenue': 75000.0,
        'profit_margin': 0.25,
        'churn_rate': 10.0,
        'intellectual_properties': ['Trademarks', 'Copyrights'],
        'competitive_advantage': 'Unique VR gameplay and strong online community.',
        'current_challenges': 'Competing with major players in the gaming industry.'
    },
    {
        'startup_company': 'AgriTech Innovations',
        'startup_website': 'https://agritechinnov.com',
        'startup_stage': 'Product-Market Fit',
        'startup_industries': ['Agritech'],
        'startup_countries': 'Kenya',
        'startup_age': 2,
        'mission': 'Leveraging technology to optimize agricultural productivity.',
        'long_term_goals': 'Enhance food security in sub-Saharan Africa.',
        'current_capital': 30000.0,
        'current_investment': 40000.0,
        'investment_needed': 50000.0,
        'business_priorities': ['Technology Enhancement', 'Geographic Expansion'],
        'founder_name': 'Grace Mumbi',
        'founder_positions': ['CEO', 'CTO'],
        'founder_gender': 'Female',
        'team_size': 12,
        'key_team_expertise': ['Tech', 'Agronomy'],
        'product_description': 'AI-powered platform for monitoring and managing farm operations.',
        'business_models': ['B2B', 'Subscription'],
        'product_stages': 'MVP',
        'monthly_users': 1200,
        'investor_attributes': ['Scalable Model', 'Positive Unit Economics'],
        'investment_round': 'Seed',
        'investor_expertise': ['Tech', 'Agronomy'],
        'engagement_lengths': ['Long-term (More than 3 years)'],
        'engagement_models': ['Hands-on'],
        'revenue_models': ['Subscription'],
        'revenue': 10000.0,
        'profit_margin': 0.15,
        'churn_rate': 7.0,
        'intellectual_properties': ['Patents'],
        'competitive_advantage': 'First mover advantage and strong local partnerships.',
        'current_challenges': 'Scaling to more regions and farmer education.'
    },
    {'startup_company': 'Startup0 Inc.', 'startup_website': 'https://startup0.com', 'startup_stage': 'MVP', 'startup_industries': ['Fintech', 'Edutainment'], 'startup_countries': 'Nigeria', 'startup_age': 3, 'mission': 'Mission statement of Startup0...', 'long_term_goals': 'Long term goals of Startup0...', 'current_capital': 43160.53491328307, 'current_investment': 47008.82321468372, 'investment_needed': 29187.881149485285, 'business_priorities': ['Marketing Spend', 'Product Development'], 'founder_name': 'Founder0 Name', 'founder_positions': ['CSO (Chief Strategy Officer)', 'CEO'], 'founder_gender': 'Female', 'team_size': 35, 'key_team_expertise': ['Marketing', 'Strategy'], 'product_description': 'Product description of Startup0...', 'business_models': ['Subscription', 'B2B'], 'product_stages': 'Prototype', 'monthly_users': 706510, 'investor_attributes': ['Large Market Size'], 'investment_round': 'Series B', 'investor_expertise': ['R&D', 'Finance', 'Product Management'], 'engagement_lengths': ['Short-term (Less than 1 year)'], 'engagement_models': ['Hands-on'], 'revenue_models': ['Direct to Consumer', 'B2G (Business to Government)'], 'revenue': 75130.70524343968, 'profit_margin': 0.21578190439894646, 'churn_rate': 13.185039617437882, 'intellectual_properties': ['Patents'], 'competitive_advantage': 'Competitive advantage of Startup0...', 'current_challenges': 'Current challenges of Startup0...'}, 
    {'startup_company': 'Startup1 Inc.', 'startup_website': 'https://startup1.com', 'startup_stage': 'Idea', 'startup_industries': ['Agritech', 'Real Estate'], 'startup_countries': 'UK', 'startup_age': 5, 'mission': 'Mission statement of Startup1...', 'long_term_goals': 'Long term goals of Startup1...', 'current_capital': 31654.901123056054, 'current_investment': 31402.168621555185, 'investment_needed': 35332.89421150711, 'business_priorities': ['Product Development'], 'founder_name': 'Founder1 Name', 'founder_positions': ['Chief Design Officer', 'Chief Product Officer'], 'founder_gender': 'Male', 'team_size': 18, 'key_team_expertise': ['Finance', 'HR', 'Tech'], 'product_description': 'Product description of Startup1...', 'business_models': ['B2C', 'B2B'], 'product_stages': 'Idea', 'monthly_users': 291731, 'investor_attributes': ['Great Team', 'Brand Recognition', 'Positive Unit Economics'], 'investment_round': 'Series B', 'investor_expertise': ['Sales'], 'engagement_lengths': ['Long-term (More than 3 years)'], 'engagement_models': ['Mentorship', 'Hands-on'], 'revenue_models': ['Marketplace'], 'revenue': 1286.5411054225228, 'profit_margin': 0.2338515955171751, 'churn_rate': 19.33734893613681, 'intellectual_properties': ['Trademarks'], 'competitive_advantage': 'Competitive advantage of Startup1...', 'current_challenges': 'Current challenges of Startup1...'}, 
    {'startup_company': 'Startup2 Inc.', 'startup_website': 'https://startup2.com', 'startup_stage': 'MVP', 'startup_industries': ['AI & ML', 'Healthtech'], 'startup_countries': 'Kenya', 'startup_age': 8, 'mission': 'Mission statement of Startup2...', 'long_term_goals': 'Long term goals of Startup2...', 'current_capital': 14084.51162467784, 'current_investment': 11652.754250820397, 'investment_needed': 12354.104604905162, 'business_priorities': ['Marketing Spend'], 'founder_name': 'Founder2 Name', 'founder_positions': ['CEO'], 'founder_gender': 'Male', 'team_size': 17, 'key_team_expertise': ['R&D', 'Strategy', 'Legal'], 'product_description': 'Product description of Startup2...', 'business_models': ['E-commerce', 'SaaS'], 'product_stages': 'Scaling', 'monthly_users': 492916, 'investor_attributes': ['Patented Technology', 'Positive Unit Economics', 'Scalable Model'], 'investment_round': 'Seed', 'investor_expertise': ['Legal'], 'engagement_lengths': ['Short-term (Less than 1 year)'], 'engagement_models': ['Strategic Partnership', 'Silent'], 'revenue_models': ['Affiliate', 'Marketplace'], 'revenue': 8205.484560195164, 'profit_margin': 0.1396333004748464, 'churn_rate': 22.21861821198882, 'intellectual_properties': ['Trade Secrets'], 'competitive_advantage': 'Competitive advantage of Startup2...', 'current_challenges': 'Current challenges of Startup2...'},
    {'startup_company': 'Startup3 Inc.', 'startup_website': 'https://startup3.com', 'startup_stage': 'Idea', 'startup_industries': ['Agritech'], 'startup_countries': 'Nigeria', 'startup_age': 3, 'mission': 'Mission statement of Startup3...', 'long_term_goals': 'Long term goals of Startup3...', 'current_capital': 22295.83293591984, 'current_investment': 48827.81270080458, 'investment_needed': 35890.8775706982, 'business_priorities': ['Hiring Talent'], 'founder_name': 'Founder3 Name', 'founder_positions': ['CEO', 'CFO'], 'founder_gender': 'Female', 'team_size': 40, 'key_team_expertise': ['Legal', 'Strategy', 'Operations'], 'product_description': 'Product description of Startup3...', 'business_models': ['B2C', 'B2B'], 'product_stages': 'Prototype', 'monthly_users': 399456, 'investor_attributes': ['Recurring Revenue', 'Brand Recognition', 'Prototype'], 'investment_round': 'Mezzanine', 'investor_expertise': ['Tech'], 'engagement_lengths': ['Long-term (More than 3 years)'], 'engagement_models': ['Hands-on', 'Strategic Partnership'], 'revenue_models': ['B2G (Business to Government)'], 'revenue': 20079.947399353383, 'profit_margin': 0.25650199192645823, 'churn_rate': 14.378412557294526, 'intellectual_properties': ['Trademarks'], 'competitive_advantage': 'Competitive advantage of Startup3...', 'current_challenges': 'Current challenges of Startup3...'}, 
    {'startup_company': 'Startup4 Inc.', 'startup_website': 'https://startup4.com', 'startup_stage': 'Scaling', 'startup_industries': ['Transportation', 'E-commerce'], 'startup_countries': 'Ghana', 'startup_age': 3, 'mission': 'Mission statement of Startup4...', 'long_term_goals': 'Long term goals of Startup4...', 'current_capital': 44304.75999866968, 'current_investment': 28788.38355134832, 'investment_needed': 17325.307308203977, 'business_priorities': ['Geographic Expansion'], 'founder_name': 'Founder4 Name', 'founder_positions': ['CIO'], 'founder_gender': 'Female', 'team_size': 42, 'key_team_expertise': ['R&D', 'Product Management', 'Strategy'], 'product_description': 'Product description of Startup4...', 'business_models': ['Subscription'], 'product_stages': 'Scaling', 'monthly_users': 437700, 'investor_attributes': ['Revenue Growth', 'Scalable Model', 'Brand Recognition'], 'investment_round': 'Mezzanine', 'investor_expertise': ['Sales'], 'engagement_lengths': ['Short-term (Less than 1 year)'], 'engagement_models': ['Silent'], 'revenue_models': ['Affiliate'], 'revenue': 28476.554008018386, 'profit_margin': 0.21317698688864534, 'churn_rate': 8.4835213314967, 'intellectual_properties': ['Trademarks', 'Copyrights'], 'competitive_advantage': 'Competitive advantage of Startup4...', 'current_challenges': 'Current challenges of Startup4...'}, 
    {'startup_company': 'Startup5 Inc.', 'startup_website': 'https://startup5.com', 'startup_stage': 'MVP', 'startup_industries': ['Education', 'GreenTech/Environment'], 'startup_countries': 'UK', 'startup_age': 7, 'mission': 'Mission statement of Startup5...', 'long_term_goals': 'Long term goals of Startup5...', 'current_capital': 20978.91970682702, 'current_investment': 42582.00310570438, 'investment_needed': 10842.899870912483, 'business_priorities': ['Customer Acquisition', 'Hiring Talent'], 'founder_name': 'Founder5 Name', 'founder_positions': ['CFO', 'CDO'], 'founder_gender': 'Female', 'team_size': 40, 'key_team_expertise': ['Finance', 'R&D'], 'product_description': 'Product description of Startup5...', 'business_models': ['Marketplace', 'E-commerce'], 'product_stages': 'Profitable', 'monthly_users': 864591, 'investor_attributes': ['Great Team', 'Large Market Size', 'Revenue Growth'], 'investment_round': 'Series B', 'investor_expertise': ['Operations'], 'engagement_lengths': ['Medium-term (1-3 years)'], 'engagement_models': ['Advisory'], 'revenue_models': ['Subscription'], 'revenue': 55164.69029547357, 'profit_margin': 0.24344071628548386, 'churn_rate': 9.0620051598003, 'intellectual_properties': ['Licensing Agreements', 'Trademarks'], 'competitive_advantage': 'Competitive advantage of Startup5...', 'current_challenges': 'Current challenges of Startup5...'}, 
    {'startup_company': 'Startup6 Inc.', 'startup_website': 'https://startup6.com', 'startup_stage': 'Mature', 'startup_industries': ['Fintech', 'AI & ML'], 'startup_countries': 'UK', 'startup_age': 3, 'mission': 'Mission statement of Startup6...', 'long_term_goals': 'Long term goals of Startup6...', 'current_capital': 44710.623468732665, 'current_investment': 29343.670209565847, 'investment_needed': 23424.43161609005, 'business_priorities': ['Technology Enhancement', 'Customer Acquisition'], 'founder_name': 'Founder6 Name', 'founder_positions': ['CIO'], 'founder_gender': 'Male', 'team_size': 29, 'key_team_expertise': ['HR'], 'product_description': 'Product description of Startup6...', 'business_models': ['B2C', 'Subscription'], 'product_stages': 'MVP', 'monthly_users': 475110, 'investor_attributes': ['Great Team'], 'investment_round': 'Series A', 'investor_expertise': ['Sales', 'Operations', 'Product Management'], 'engagement_lengths': ['Short-term (Less than 1 year)'], 'engagement_models': ['Hands-on', 'Advisory'], 'revenue_models': ['B2B', 'SaaS'], 'revenue': 52336.33261920988, 'profit_margin': 0.23076375997043885, 'churn_rate': 22.775275780445643, 'intellectual_properties': ['Design Rights'], 'competitive_advantage': 'Competitive advantage of Startup6...', 'current_challenges': 'Current challenges of Startup6...'}, 
    {'startup_company': 'Startup7 Inc.', 'startup_website': 'https://startup7.com', 'startup_stage': 'Scaling', 'startup_industries': ['E-sports'], 'startup_countries': 'USA', 'startup_age': 3, 'mission': 'Mission statement of Startup7...', 'long_term_goals': 'Long term goals of Startup7...', 'current_capital': 40465.08855989277, 'current_investment': 34962.42894892534, 'investment_needed': 19981.419739979763, 'business_priorities': ['Prototype Development'], 'founder_name': 'Founder7 Name', 'founder_positions': ['CDO'], 'founder_gender': 'Male', 'team_size': 27, 'key_team_expertise': ['Sales', 'Operations'], 'product_description': 'Product description of Startup7...', 'business_models': ['SaaS'], 'product_stages': 'Scaling', 'monthly_users': 231290, 'investor_attributes': ['Great Team', 'Patented Technology'], 'investment_round': 'Bridge Round', 'investor_expertise': ['Operations', 'Marketing'], 'engagement_lengths': ['Short-term (Less than 1 year)'], 'engagement_models': ['Strategic Partnership'], 'revenue_models': ['Marketplace', 'B2G (Business to Government)'], 'revenue': 38770.75283682, 'profit_margin': 0.2742391074341325, 'churn_rate': 20.968512065878603, 'intellectual_properties': ['Patents'], 'competitive_advantage': 'Competitive advantage of Startup7...', 'current_challenges': 'Current challenges of Startup7...'}, 
    {'startup_company': 'Startup8 Inc.', 'startup_website': 'https://startup8.com', 'startup_stage': 'Mature', 'startup_industries': ['Insuretech', 'Foodtech'], 'startup_countries': 'UK', 'startup_age': 8, 'mission': 'Mission statement of Startup8...', 'long_term_goals': 'Long term goals of Startup8...', 'current_capital': 11386.901451450794, 'current_investment': 44044.33898399349, 'investment_needed': 45443.535145208676, 'business_priorities': ['Marketing Spend', 'Prototype Development'], 'founder_name': 'Founder8 Name', 'founder_positions': ['CTO', 'COO'], 'founder_gender': 'Male', 'team_size': 21, 'key_team_expertise': ['Product Management'], 'product_description': 'Product description of Startup8...', 'business_models': ['E-commerce'], 'product_stages': 'Scaling', 'monthly_users': 411305, 'investor_attributes': ['Large Market Size'], 'investment_round': 'Mezzanine', 'investor_expertise': ['Product Management'], 'engagement_lengths': ['Long-term (More than 3 years)'], 'engagement_models': ['Hands-on', 'Mentorship'], 'revenue_models': ['Subscription', 'B2B'], 'revenue': 141.13760465167547, 'profit_margin': 0.058989570807803135, 'churn_rate': 7.116455011046492, 'intellectual_properties': ['Design Rights', 'Copyrights'], 'competitive_advantage': 'Competitive advantage of Startup8...', 'current_challenges': 'Current challenges of Startup8...'}, 
    {'startup_company': 'Startup9 Inc.', 'startup_website': 'https://startup9.com', 'startup_stage': 'MVP', 'startup_industries': ['Transportation'], 'startup_countries': 'USA', 'startup_age': 4, 'mission': 'Mission statement of Startup9...', 'long_term_goals': 'Long term goals of Startup9...', 'current_capital': 30366.691125525795, 'current_investment': 25962.1720119491, 'investment_needed': 18906.4085116512, 'business_priorities': ['Prototype Development'], 'founder_name': 'Founder9 Name', 'founder_positions': ['CSO (Chief Strategy Officer)', 'COO'], 'founder_gender': 'Female', 'team_size': 24, 'key_team_expertise': ['Finance'], 'product_description': 'Product description of Startup9...', 'business_models': ['B2C'], 'product_stages': 'Prototype', 'monthly_users': 57621, 'investor_attributes': ['Initial Customers'], 'investment_round': 'Series C', 'investor_expertise': ['Tech', 'Operations'], 'engagement_lengths': ['Short-term (Less than 1 year)'], 'engagement_models': ['Strategic Partnership'], 'revenue_models': ['E-commerce', 'Affiliate'], 'revenue': 59032.034243384645, 'profit_margin': 0.2458534841720127, 'churn_rate': 13.893358130730105, 'intellectual_properties': ['Patents'], 'competitive_advantage': 'Competitive advantage of Startup9...', 'current_challenges': 'Current challenges of Startup9...'}, 
    {'startup_company': 'Startup10 Inc.', 'startup_website': 'https://startup10.com', 'startup_stage': 'Mature', 'startup_industries': ['E-sports', 'Transportation'], 'startup_countries': 'Nigeria', 'startup_age': 3, 'mission': 'Mission statement of Startup10...', 'long_term_goals': 'Long term goals of Startup10...', 'current_capital': 48246.6688667853, 'current_investment': 29283.716526509015, 'investment_needed': 11850.978395372507, 'business_priorities': ['Customer Acquisition'], 'founder_name': 'Founder10 Name', 'founder_positions': ['CIO', 'CDO'], 'founder_gender': 'Female', 'team_size': 40, 'key_team_expertise': ['Product Management', 'Strategy'], 'product_description': 'Product description of Startup10...', 'business_models': ['SaaS'], 'product_stages': 'Profitable', 'monthly_users': 755558, 'investor_attributes': ['Scalable Model', 'Patented Technology', 'Revenue Growth'], 'investment_round': 'Series C', 'investor_expertise': ['Legal', 'Product Management'], 'engagement_lengths': ['Short-term (Less than 1 year)'], 'engagement_models': ['Silent'], 'revenue_models': ['Affiliate', 'Marketplace'], 'revenue': 48203.71401989706, 'profit_margin': 0.1186798912806457, 'churn_rate': 19.797755110855245, 'intellectual_properties': ['Trade Secrets', 'Patents'], 'competitive_advantage': 'Competitive advantage of Startup10...', 'current_challenges': 'Current challenges of Startup10...'}, 
    {'startup_company': 'Startup11 Inc.', 'startup_website': 'https://startup11.com', 'startup_stage': 'Scaling', 'startup_industries': ['Immersive Entertainment and Technology', 'Edutainment'], 'startup_countries': 'South Africa', 'startup_age': 6, 'mission': 'Mission statement of Startup11...', 'long_term_goals': 'Long term goals of Startup11...', 'current_capital': 49631.31303331477, 'current_investment': 13339.696497796122, 'investment_needed': 33894.50490142149, 'business_priorities': ['Prototype Development'], 'founder_name': 'Founder11 Name', 'founder_positions': ['CMO', 'COO'], 'founder_gender': 'Female', 'team_size': 21, 'key_team_expertise': ['Finance', 'Operations', 'Legal'], 'product_description': 'Product description of Startup11...', 'business_models': ['Subscription'], 'product_stages': 'Post-Revenue', 'monthly_users': 556661, 'investor_attributes': ['Scalable Model', 'Positive Unit Economics'], 'investment_round': 'Seed', 'investor_expertise': ['R&D'], 'engagement_lengths': ['Short-term (Less than 1 year)'], 'engagement_models': ['Mentorship', 'Hands-on'], 'revenue_models': ['Affiliate', 'B2G (Business to Government)'], 'revenue': 32257.28074300328, 'profit_margin': 0.2166026457609629, 'churn_rate': 15.856800255922796, 'intellectual_properties': ['Trademarks'], 'competitive_advantage': 'Competitive advantage of Startup11...', 'current_challenges': 'Current challenges of Startup11...'}, 
    {'startup_company': 'Startup12 Inc.', 'startup_website': 'https://startup12.com', 'startup_stage': 'MVP', 'startup_industries': ['Foodtech', 'Fintech'], 'startup_countries': 'Kenya', 'startup_age': 3, 'mission': 'Mission statement of Startup12...', 'long_term_goals': 'Long term goals of Startup12...', 'current_capital': 49681.054499853206, 'current_investment': 17233.46641131873, 'investment_needed': 20237.909423852783, 'business_priorities': ['Geographic Expansion'], 'founder_name': 'Founder12 Name', 'founder_positions': ['CFO'], 'founder_gender': 'Female', 'team_size': 17, 'key_team_expertise': ['Sales', 'Marketing'], 'product_description': 'Product description of Startup12...', 'business_models': ['B2G (Business to Government)'], 'product_stages': 'Post-Revenue', 'monthly_users': 137209, 'investor_attributes': ['Prototype', 'Initial Customers', 'Brand Recognition'], 'investment_round': 'Mezzanine', 'investor_expertise': ['Product Management', 'Tech', 'Legal'], 'engagement_lengths': ['Medium-term (1-3 years)'], 'engagement_models': ['Advisory', 'Silent'], 'revenue_models': ['Affiliate'], 'revenue': 63231.47790142128, 'profit_margin': 0.08254760462875095, 'churn_rate': 14.547531987346291, 'intellectual_properties': ['Trademarks', 'Copyrights'], 'competitive_advantage': 'Competitive advantage of Startup12...', 'current_challenges': 'Current challenges of Startup12...'}, 
    {'startup_company': 'Startup13 Inc.', 'startup_website': 'https://startup13.com', 'startup_stage': 'Scaling', 'startup_industries': ['Healthtech', 'E-sports'], 'startup_countries': 'Nigeria', 'startup_age': 6, 'mission': 'Mission statement of Startup13...', 'long_term_goals': 'Long term goals of Startup13...', 'current_capital': 27735.942177630335, 'current_investment': 23189.987255356617, 'investment_needed': 23947.548351626665, 'business_priorities': ['Prototype Development', 'Marketing Spend'], 'founder_name': 'Founder13 Name', 'founder_positions': ['Chief Product Officer', 'CIO'], 'founder_gender': 'Male', 'team_size': 13, 'key_team_expertise': ['Operations'], 'product_description': 'Product description of Startup13...', 'business_models': ['Direct to Consumer'], 'product_stages': 'Idea', 'monthly_users': 198880, 'investor_attributes': ['Initial Customers', 'Recurring Revenue'], 'investment_round': 'Series C', 'investor_expertise': ['Sales', 'HR'], 'engagement_lengths': ['Long-term (More than 3 years)'], 'engagement_models': ['Mentorship', 'Strategic Partnership'], 'revenue_models': ['B2C', 'Direct to Consumer'], 'revenue': 50310.20035277442, 'profit_margin': 0.08785347054226901, 'churn_rate': 20.19558926857726, 'intellectual_properties': ['Patents', 'Trade Secrets'], 'competitive_advantage': 'Competitive advantage of Startup13...', 'current_challenges': 'Current challenges of Startup13...'}
]
